# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_API', '0002_auto_20180721_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='to',
            field=models.BooleanField(default=False),
        ),
    ]
