# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_API', '0003_auto_20180721_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='region',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
