# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_API', '0004_option_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='region',
            field=models.BooleanField(),
        ),
    ]
